### ISSUE TITLE
learned parameter=false

### ISSUE THREAD

**Issue by gFazzari** [ZachChristensen28/TA-crowdstrike-identities#29]
### Bug description

Hi Zach!

I don't know if this is a bug or a feature..
In your GraphQL query you set "learned=false" and this limits a lot your results based on Crowdstrike learning status. 
Is there a motivation behind this choice?
Thanks in advance.

### Related links

- [Example Issue](https://splunk-ta-crowdstrike.ztsplunker.com/)

### TA-crowdstrike-identities Version

1.0.0

### Splunk Version

9.0.1

**Comment by ZachChristensen28** [comment]
Thanks for pointing this out. This is a legacy artifact from the falconpy scripts. This would probably be best to be removed.
