### ISSUE TITLE
Not all identities being pulled

### ISSUE THREAD

**Issue by kbostater3** [ZachChristensen28/TA-crowdstrike-identities#32]
### Bug description

Only about 9000 of our 13000 identities are being pulled in. It's not a dedup error, because some of our samAccountNames that exist in multiple domains are showing up more than once. The most complete domain "CACHEMAIL.EXT" is also the most useless. Blacklisting that domain does not lead to more entries from other domains being ingested.

### Related links

- [Example Issue](https://splunk-ta-crowdstrike.ztsplunker.com/)
-[Running index=_internal sourcetype="tacrowdstrikeidentities:log" produces no errors] (https://splunk-ta-crowdstrike.ztsplunker.com/troubleshoot/)

### TA-crowdstrike-identities Version

1.0.2

### Splunk Version

9.0.2303.201

**Comment by ZachChristensen28** [comment]
This may be related to issue #29. The default behavior is to only pull in devices that are not learned by CrowdStrike. This setting will be removed in the next version. Remove "learned: false" from the GraphQL call in the python the script and see if that makes a difference. https://github.com/ZachChristensen28/TA-crowdstrike-identities/blob/3d7812af8a653b89c97ccd96b58bc4f34c0fca01/src/TA-crowdstrike-identities/bin/input_module_crowdstrike_identities.py#L72

**Comment by kbostater3** [comment]
We're using Splunk GovCloud. I asked Splunk Support to make that change, but they refused because it's a developer supported app.

**Comment by ZachTheSplunker** [comment]
The new version was just released with the fix. It should be available in Splunk Gov Cloud after the appinspect runs. Could take 2 - 5 days. https://splunkbase.splunk.com/app/6893
