### ISSUE TITLE
Availability in Splunk Cloud

### ISSUE THREAD

**Issue by kcotter-cyber** [ZachChristensen28/TA-crowdstrike-identities#34]
### Bug description

I noticed for 1.0.3 the app does not seem to be available for Splunk Cloud like 1.0.2 was in Splunkbase. Will this be changed in the future?

### Related links

https://splunkbase.splunk.com/app/6893

### TA-crowdstrike-identities Version

1.0.3

### Splunk Version

9.1.2308

**Comment by ZachChristensen28** [comment]
Splunkbase is still vetting the recently released version. This process could take some time after each release.
